### ISSUE TITLE
catkin_make error

### ISSUE THREAD

**Issue by sunt40** [ibtisamtauhidi/ca-cc#1]
I catkin_make your code with ROS-kinetic,the error is as follow:
ca-cc-master/src/SendGoal.cpp:2:43: fatal error: move_base_msgs/MoveBaseAction.h: 没有那个文件或目录
How to get the MoveBaseAction.hfile?
@ibtisamtauhidi

**Comment by sitauhidi** [comment]
Which ROS version are you using?

On 17-May-2019 07:23, sunt40 <notifications@github.com> wrote:

I catkin_make your code with ROS-kinetic,the error is as follow:
ca-cc-master/src/SendGoal.cpp:2:43: fatal error: move_base_msgs/MoveBaseAction.h: 没有那个文件或目录
How to get the MoveBaseAction.hfile?
@ibtisamtauhidi<https://github.com/ibtisamtauhidi>

**Comment by sunt40** [comment]
I  run it with ROS kinetic. @ibtisamtauhidi

**Comment by sunt40** [comment]
I did not find the MoveBaseAction.h file in your code.Could you please tell me how to find this file?
@ibtisamtauhidi
